### ISSUE TITLE
Stomp in node with ws gives memory leak when using msg body

### ISSUE THREAD

**Issue by jonim8or** [stomp-js/stompjs#253]
I have a memory leak in my code, when using stompjs with activeMQ. I managed to boil it down to a minimal example:
No memory leak:
```    
    client.subscribe('/topic/general', () => {
        console.log(`received: ${i++}\`);
    });
```
Memory leak:
```
    client.subscribe('/topic/general', (msg)=>{
        console.log(``received: ${msg.body.substr(0,20)}``);
    });
```
attached zip contains the minimal example. You will need to start an activeMQ classic at ws://localhost:61614 
then do
`
npm install
npm run test
`
This will start a process that sends messages to a topic, and two processes (the working and the leaking one) that listen to it
The processes will save heapprofile and heapsnapshot every 5 mins
The zip also contains heapsnapshots and heapprofiles at startup and after 5 minutes

[stompMemLeak.zip](https://github.com/stomp-js/stompjs/files/4902976/stompMemLeak.zip)

**Comment by kum-deepak** [comment]
This is going to be my first experience in dealing with memory leak in Javascript. I have gone through your heap reports, which seem to be quite useful. Thanks!

As per this report, the leak might be in `TextDecoder`, which is provided by the runtime. Sometime in Node 11, this library was bundled. The first thing I will ask you to test is to use the polyfill so that Node's TextEncoder/Decoder is not used. Please see https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/pollyfils-for-stompjs-v5.html#in-nodejs.

I will also ask you to test with https://github.com/samthor/fast-text-encoding  as the original text-encoding is no longer maintained. This will help isolate the problem and allow me to resolve it.

Also, let me know which version of Node are you using.

**Comment by kum-deepak** [comment]
Check your Node version to see if it relates to https://github.com/nodejs/node/issues/32424

**Comment by jonim8or** [comment]
Hi,
The leak was occurring in node 12.16.2 and seems to not occur in 12.18.2 so I think your link solves the issue. I'll make sure to update my node versions.

Thanks for your time, and your work on the library!
