### ISSUE TITLE
Subscription is lost after some time but no event is sent

### ISSUE THREAD

**Issue by aloiseau17** [stomp-js/stompjs#344]
Hello,
I'm implementing websocket application using stomp and sockjs on front side. Back side is developed with spring (simple broker).

**Normal situation:**
There are several clients connected to the websocket server. Every client subscribe to the same topic channel, let say `/topic/update`. 
The server send a message to each client (different for each based on a uniq id). Every client receive a MESSAGE frame with specific informations.

**Issue:**
Sometimes, for no reason, one or several clients stop receiving MESSAGE frame from the subscribed channel. There is no log or event called (front and back). The client is still able to send MESSAGE to the server and heartbeat mechanism is still working. So the connection is still opened.

I really don't know where and what to search. If anyone has any idea I'll be very gratefull 🙏🏻

**Comment by kum-deepak** [comment]
Please enable debug and set https://stomp-js.github.io/api-docs/latest/classes/Client.html#logRawCommunication to `true` (it can be set via configuration). This enables logging of the underlying data sent and received by the client. Attach the output.

In addition, if possible use plain Websockets instead of using SockJS compatibility. See https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

**Comment by aloiseau17** [comment]
Thank you very much for your reply @kum-deepak.
I've enabled `debug` and `logRawCommunication` (this one wasn't enable yet). But no extra log is displayed.
We are testing to deploy the app on a completely fresh instance. The bug seems to not happen for now. So maybe it's due to a network configuration or somethings self-reliant.
Let see in few days if the problem reappear. I'll reply on this conversation if it'll be the case.
