### ISSUE TITLE
Webscoket doesnot tries to reconnect when wifi is turned off or internet is lost, Due to which when  network is back  client stops receiving msg over socket but still able to send to othew clients.

### ISSUE THREAD

**Issue by ajayshah1992** [stomp-js/stompjs#350]
Webscoket doesnot tries to reconnect when wifi is turned off or internet is lost, Due to which when  network is back  client stops receiving msg over socket but still able to send to othew clients.

When I am bring server down at that time also WS is not closed cleanly and another Connect opened, some time even multiple, but receiving msgs on latest one only.

**Comment by kum-deepak** [comment]
There are two ways the library detects that the WebSocket connection is no longer valid:

- The websocket raises onclose callback,
- or, the heartbeat fails.

SockJS does not support either of these reliably. So, my first suggestion will be to use Websockets as the underlying connection instead of SockJS. Please read https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/using-stomp-with-sockjs.html

On the other hand please attach your entire log, I need to see the server responses, heartbeat etc. The file may be big, please attach as a text file.

**Comment by ajayshah1992** [comment]
Thanks for quick response.
As I have not found any concrete solution, I have done some work around to handle some connection drop scenario by implementing  connection check of Backend server with an open api and same for wifi network too.

Here is my piece of code

        this.connectionService.monitor().subscribe(currentState => {
           /* console.log("internet State>>>> ", currentState, "STOMP broker", this.stompService.connected(), "client is active ", this.stompService.active)*/
            if (!currentState.hasInternetAccess || !currentState.hasNetworkConnection) {
                if(this.stompService.active) {
                    this.stompService.deactivate();
                }
            } else if (currentState.hasInternetAccess && currentState.hasNetworkConnection) {
                if(!this.stompService.active) {
                    this.stompService.activate();
                }

                /* if (!this.stompService.stompClient) {
                     this.stompService.activate();
                 }*/
            }
        });


This setup had handle my case for now. But for proper solution would consider your suggesstion for droping sockjs  at some point and to use websocket protocals.

Thank you
