### ISSUE TITLE
One and the same message is perceived as 2, with different ID but with the difference of one number at the end.

### ISSUE THREAD

**Issue by Sinevik** [stomp-js/stompjs#625]
`"react": "^17.0.0"`
"@stomp/stompjs": "^7.0.0",
[Google Chrome]

![image](https://github.com/stomp-js/stompjs/assets/27360744/b76c1dbd-aeb1-4f4c-ae91-ebfd7bea2937)

In the console, it comes up with 1 message
![image](https://github.com/stomp-js/stompjs/assets/27360744/dbd2e863-ab5c-4448-9122-5f3832053f89)

But in the code, this message is perceived as 2 with the difference of one number at the end

![image](https://github.com/stomp-js/stompjs/assets/27360744/6bc69fcd-0f15-48fa-8dd4-56724e63b8af)

The problem doesn't always arise. But when it does occur it has a common pattern with a difference of 1 digit at the end

**Comment by kum-deepak** [comment]
Please check your console output (your screenshot corresponds to packets from only one WebSocket). It is quite likely that your code created two stomp clients. Each subscribed once, so you are seeing two messages in the code.

This issue was reported earlier as well. I noticed in React documentation why it runs twice - https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

I usually do not program with React, and I do not use this library with React. So, I got someone to prepare a sample to use this library with React. This structure does not suffer from this problem. In addition, it also covers the case when child components use the client.

Please see https://github.com/stomp-js/rx-stomp-react-sample - start with src/App.js

This sample uses rxStomp - a wrapper over stompjs. The key difference between the two is that in stompjs, the communication methods like subscribe can only be called from within the onConnect callback, while in rxStomp, these can be called anywhere.

**Comment by Sinevik** [comment]
`It is quite likely that your code created two stomp clients`
If that were the case, we'd be seeing 2 subscriptions in the console. But they're not.
![image](https://github.com/stomp-js/stompjs/assets/27360744/55510629-342b-4a5f-ae6e-2bdf3b4631e0)

This link leads nowhere. Could you please add an actual link
https://github.com/stomp-js/rx-stomp-react-sample

**Comment by kum-deepak** [comment]
Sorry for my mistake. The repository was marked private. Please access it at https://github.com/stomp-js/rx-stomp-react-sample

Your screenshot is not the console log; it is WebSocket messages (probably from the Network tab in Chrome). Please enable debug output for this library and check the console log. In Chrome, the console will look like the following:

![Screenshot from 2024-02-22 20-01-22](https://github.com/stomp-js/stompjs/assets/3807337/8f88b65b-a3b6-4da9-915a-9b5c5eb06da7)
