### ISSUE TITLE
Client.debug message does not contain body

### ISSUE THREAD

**Issue by coyot** [stomp-js/stompjs#84]
When writing the debug message to console - the content-length is written two times rather than the body of a message. 

using

```
client.debug = (msg) => {
  console.log(msg);
};
```

the msg string - does not have the body to be written to console.

**Comment by kum-deepak** [comment]
Please attach entire console output (you will need to attach it as a file, as it is \0 (NULLs)).

**Comment by coyot** [comment]
It's unfortunately forbidden by NDA. But it looks like this: 

```
<<< MESSAGE
content-length:123
message-id:123444
subscription:sub-1
content-type:application/json;charset=UTF-8
destination:my/queue
content-length:123
(empty line here)
```

In previous version we used it was more or less
```
<<< MESSAGE
content-length:123
message-id:123444
subscription:sub-1
content-type:application/json;charset=UTF-8
destination:my/queue
content-length:123

{ json_of_an_object }
```

There is obviously workaround - but I don't think change in the library was intentional, was it?

**Comment by kum-deepak** [comment]
This is an intentional change. To get roughly the old behavior please set `logRawCommunication` to `true` in your config (see the note at https://stomp-js.github.io/api-docs/latest/classes/Client.html#logRawCommunication)

The current version supports binary data in STOMP communication. The previous version just assumed everything to be valid UTF8. For that reason in older version the entire raw communication was simply added to the console. In the current version, it was messing up heavily if the frames were binary.
